### ISSUE TITLE
Add integration tests between backend api and executor lambda

### ISSUE THREAD

**Issue by limanjun99** [huajun07/codesketcher#40]
As highlighted in this [issue](https://github.com/huajun07/codesketcher/issues/39), there is a real need for integration testing of the executor lambda.

To avoid slowing down our tests, we should only run a few integrations testcases for sanity checks. Majority of the testcases will still be unit tests in the executor service, which run very quickly.

**Comment by huajun07** [comment]
Resolved via #78
